/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cochinitoDigital;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lizbeth Flores Tomas Ascencio
 */
public class VistaAlcancia extends javax.swing.JFrame {

    ArrayList<Monedas> CochinitoDigital = new ArrayList<Monedas>();
    Date fecha = new Date();
    Monedas moneda;
    Alcancia alcancia;
    double total;
    String fechaRomper = fecha.toString();
    String nombre = "";

    public VistaAlcancia() {
        initComponents();

        this.setLocationRelativeTo(null);

        alcancia = new Alcancia();

        //Agrupar botones en un botomGroup
        buttonGroup.add(rbCincuentaCentavos);
        buttonGroup.add(rbUno);
        buttonGroup.add(rbDos);
        buttonGroup.add(rbCinco);
        buttonGroup.add(rbDiez);

        btnNuevaAlcancia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanelMonedas = new javax.swing.JPanel();
        rbCincuentaCentavos = new javax.swing.JRadioButton();
        rbUno = new javax.swing.JRadioButton();
        rbDos = new javax.swing.JRadioButton();
        rbCinco = new javax.swing.JRadioButton();
        rbDiez = new javax.swing.JRadioButton();
        btnAgregar = new java.awt.Button();
        jPanelRompeAlcancia = new javax.swing.JPanel();
        btnRomper = new javax.swing.JButton();
        lblPropietario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnNuevaAlcancia = new java.awt.Button();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelAlcancia = new javax.swing.JPanel();
        lblCochinito = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSaldoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alcancia Virtual");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMonedas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)), "Monedas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanelMonedas.setName(""); // NOI18N

        rbCincuentaCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/moneda50.jpg"))); // NOI18N
        rbCincuentaCentavos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCincuentaCentavosMouseClicked(evt);
            }
        });

        rbUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda1.jpg"))); // NOI18N
        rbUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUnoActionPerformed(evt);
            }
        });

        rbDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda2.jpg"))); // NOI18N
        rbDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDosActionPerformed(evt);
            }
        });

        rbCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda5.jpg"))); // NOI18N
        rbCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCincoActionPerformed(evt);
            }
        });

        rbDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda10.jpg"))); // NOI18N
        rbDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiezActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 102, 115));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregar.setLabel("Agregar Moneda");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMonedasLayout = new javax.swing.GroupLayout(jPanelMonedas);
        jPanelMonedas.setLayout(jPanelMonedasLayout);
        jPanelMonedasLayout.setHorizontalGroup(
            jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonedasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbCincuentaCentavos)
                .addGap(18, 18, 18)
                .addComponent(rbUno)
                .addGap(22, 22, 22)
                .addComponent(rbDos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbDiez, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelMonedasLayout.setVerticalGroup(
            jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonedasLayout.createSequentialGroup()
                .addGroup(jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbUno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(rbCincuentaCentavos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(rbCinco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbDiez, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMonedasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 770, 120));
        jPanelMonedas.getAccessibleContext().setAccessibleName("");

        jPanelRompeAlcancia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 119, 73)), "Romper Alcancia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 1, 14), new java.awt.Color(230, 0, 38))); // NOI18N

        btnRomper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/martillo1.png"))); // NOI18N
        btnRomper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomperActionPerformed(evt);
            }
        });

        lblPropietario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPropietario.setText("Propietario: ");
        lblPropietario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFecha.setText("Fecha: ----/-----/-----");

        btnNuevaAlcancia.setBackground(new java.awt.Color(255, 102, 115));
        btnNuevaAlcancia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevaAlcancia.setLabel("Nueva Alcancia");
        btnNuevaAlcancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaAlcanciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRompeAlcanciaLayout = new javax.swing.GroupLayout(jPanelRompeAlcancia);
        jPanelRompeAlcancia.setLayout(jPanelRompeAlcanciaLayout);
        jPanelRompeAlcanciaLayout.setHorizontalGroup(
            jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaAlcancia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPropietario)
                    .addComponent(btnRomper, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelRompeAlcanciaLayout.setVerticalGroup(
            jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRomper, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPropietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevaAlcancia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanelRompeAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 270, 370));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 215, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Alcancia Digital");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jPanelAlcancia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 119, 73)), "Alcancia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic Semilight", 3, 14), new java.awt.Color(230, 0, 38))); // NOI18N

        lblCochinito.setBackground(new java.awt.Color(0, 204, 204));
        lblCochinito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cochinito.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelAlcanciaLayout = new javax.swing.GroupLayout(jPanelAlcancia);
        jPanelAlcancia.setLayout(jPanelAlcanciaLayout);
        jPanelAlcanciaLayout.setHorizontalGroup(
            jPanelAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCochinito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAlcanciaLayout.setVerticalGroup(
            jPanelAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCochinito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, 300));

        lblSaldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 0, 0));
        lblSaldo.setText("En la alcancia hay:");
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 130, 50));

        lblSaldoTotal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblSaldoTotal.setForeground(new java.awt.Color(255, 215, 0));
        getContentPane().add(lblSaldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 144, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        total = alcancia.ContarMonedas(alcancia.AbrirArchivo(), 0.0);
        lblSaldoTotal.setText("$" + total);
        try {
            if (alcancia.LeerFecha() == "") {

                nombre = JOptionPane.showInputDialog("POR FAVOR INGRESA TU NOMBRE: ");
                if (nombre.equals("")) {
                    btnAgregar.setVisible(false);
                    btnRomper.setVisible(false);
                    btnNuevaAlcancia.setVisible(true);
                } 
                else {
                    fechaRomper = alcancia.LeerFecha();
                    String[] stringRomper = fechaRomper.split(" ");
                    lblPropietario.setText("PROPIETARIO: " + stringRomper[1]);
                    lblFecha.setText(stringRomper[0]);
                }
            } else {
                fechaRomper = alcancia.LeerFecha();
                String[] cortarString = fechaRomper.split("  ");
                lblPropietario.setText("PROPIETARIO: " + cortarString[1]);
                lblFecha.setText(cortarString[0]);
            }
        } catch (IOException ex) {
            Logger.getLogger(VistaAlcancia.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    /**
     * *Metodo que cambia el icono del radio boton para **detectar visualmente
     * cual esta seleccionado**
     */
    private void rbCincuentaCentavosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCincuentaCentavosMouseClicked
        rbCincuentaCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda50_1.jpg")));
        rbUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda1.jpg")));
        rbDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda2.jpg")));
        rbCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda5.jpg")));
        rbDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda10.jpg")));
    }//GEN-LAST:event_rbCincuentaCentavosMouseClicked

    private void rbUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUnoActionPerformed
        rbCincuentaCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda50.jpg")));
        rbUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda1_1.jpg")));
        rbDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda2.jpg")));
        rbCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda5.jpg")));
        rbDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda10.jpg")));
    }//GEN-LAST:event_rbUnoActionPerformed

    private void rbDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDosActionPerformed
        rbCincuentaCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda50.jpg")));
        rbUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda1.jpg")));
        rbDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda2_1.jpg")));
        rbCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda5.jpg")));
        rbDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda10.jpg")));
    }//GEN-LAST:event_rbDosActionPerformed

    private void rbCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCincoActionPerformed
        rbCincuentaCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda50.jpg")));
        rbUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda1.jpg")));
        rbDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda2.jpg")));
        rbCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda5_1.jpg")));
        rbDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda10.jpg")));
    }//GEN-LAST:event_rbCincoActionPerformed

    private void rbDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiezActionPerformed
        rbCincuentaCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda50.jpg")));
        rbUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda1.jpg")));
        rbDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda2.jpg")));
        rbCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda5.jpg")));
        rbDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moneda10_1.jpg")));
    }//GEN-LAST:event_rbDiezActionPerformed
    /**
     * *Metodo que cambia el icono del radio boton para **detectar visualmente
     * cual esta seleccionado**
     */

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        MonedaSeleccionada();
        lblSaldoTotal.setText("$" + alcancia.ContarMonedas(CochinitoDigital, total));
    }//GEN-LAST:event_btnAgregarMouseClicked

    /*Cuando se da en el boton para cerrar la ventana despliega un
     mensaje con el total ahorrado en la alcancia    *****/

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        alcancia.GuardarEnArchivo(CochinitoDigital);

    }//GEN-LAST:event_formWindowClosing

    private void btnRomperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomperActionPerformed
        int opt = JOptionPane.showConfirmDialog(rootPane, "QUIERES ROMPER LA ALCANCIA");
        if (JOptionPane.OK_OPTION == opt) {
            alcancia.RomperAlcancia();
            lblCochinito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cochinitoRoto.jpg")));
            btnRomper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UACM.jpg")));
            JOptionPane.showMessageDialog(rootPane, "EL TOTAL AHORRADO  ES DE:"+ "$" + alcancia.ContarMonedas(CochinitoDigital, total));
            total = 0;
            CochinitoDigital.clear();
            lblSaldoTotal.setText("$" + total);
            lblPropietario.setText("PROPIETARIO: ");
            lblFecha.setText("FECHA: ");
            btnAgregar.setVisible(false);

            btnNuevaAlcancia.setVisible(true);

        }
    }//GEN-LAST:event_btnRomperActionPerformed

    private void btnNuevaAlcanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaAlcanciaMouseClicked
        btnRomper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/martillo1.png")));
        btnAgregar.setVisible(true);
        btnRomper.setVisible(true);
        btnNuevaAlcancia.setVisible(false);
        fechaRomper = fecha.toString();
        nombre = JOptionPane.showInputDialog("INGRESA TU NOMBRE: ");
        if (nombre.equals("")) {
            btnAgregar.setVisible(false);
            btnRomper.setVisible(false);
            btnNuevaAlcancia.setVisible(true);
        } else {
            lblCochinito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cochinito.jpg")));
            lblPropietario.setText("PROPIETARIO: " + nombre);
            lblFecha.setText(fechaRomper);
            alcancia.GuardarFecha(fechaRomper + "  " + nombre);
            btnAgregar.setVisible(true);
            btnRomper.setVisible(true);
            btnNuevaAlcancia.setVisible(false);
            fechaRomper = fecha.toString();
        }
    }//GEN-LAST:event_btnNuevaAlcanciaMouseClicked

    public void MonedaSeleccionada() {
        if (rbCincuentaCentavos.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 50 CENTAVOS");
            moneda = new Monedas(.50);
            CochinitoDigital.add(moneda);
        }
        if (rbUno.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 1 PESOS");
            moneda = new Monedas(1);
            CochinitoDigital.add(moneda);
        }
        if (rbDos.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 2 PESOS");
            moneda = new Monedas(2);
            CochinitoDigital.add(moneda);
        }
        if (rbCinco.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 5 PESOS");
            moneda = new Monedas(5);
            CochinitoDigital.add(moneda);
        }
        if (rbDiez.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 10 PESOS");
            moneda = new Monedas(10);
            CochinitoDigital.add(moneda);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlcancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAgregar;
    private java.awt.Button btnNuevaAlcancia;
    private javax.swing.JButton btnRomper;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAlcancia;
    private javax.swing.JPanel jPanelMonedas;
    private javax.swing.JPanel jPanelRompeAlcancia;
    private javax.swing.JLabel lblCochinito;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoTotal;
    private javax.swing.JRadioButton rbCinco;
    private javax.swing.JRadioButton rbCincuentaCentavos;
    private javax.swing.JRadioButton rbDiez;
    private javax.swing.JRadioButton rbDos;
    private javax.swing.JRadioButton rbUno;
    // End of variables declaration//GEN-END:variables
}
